api_root_path: ''
auto_reload: false
client_id: test-client
cors_allow_credentials: null
cors_allowed_headers: null
cors_allowed_methods: null
cors_allowed_origins: null
docs_url: /docs
generate_correlation_id: true
host: 0.0.0.0
issuer: https://op.test/
log_format: null
log_level: INFO
openapi_url: /openapi.json
port: 8080
service_instance_id: '1'
service_name: top
user_domain: home.org
valid_seconds: 3600
workers: 1
