[project]
name = "top"
version = "1.1.0"
description = "Test OpenID Connect provider"
dependencies = [
    "typer >= 0.9.0",
    "ghga-service-commons[api] >= 1.2.0",
    "hexkit >= 1.1.0"
]

[project.urls]
Repository = "https://github.com/ghga-de/test-oidc-provider"

[project.scripts]
top = "top.__main__:run"
