[project]
name = "top"
version = "1.2.0"
description = "Test OpenID Connect provider"
dependencies = [
    "typer >= 0.12",
    "ghga-service-commons[api,auth] >= 3.1.5, < 4",
    "hexkit >= 3.2.2, < 4"
]

[project.urls]
Repository = "https://github.com/ghga-de/test-oidc-provider"

[project.scripts]
top = "top.__main__:run"
