[project]
name = "top"
version = "2.1.0"
description = "Test OpenID Connect provider"
dependencies = [
    "typer >= 0.15",
    "ghga-service-commons[api,auth] >= 4, < 5",
    "hexkit >= 4.6, < 5",
    "python-multipart >= 0.0.20"
]

[project.urls]
Repository = "https://github.com/ghga-de/test-oidc-provider"

[project.scripts]
top = "top.__main__:run"
